nohup python train.py \
    --model_type gpt2 \
    --config_path ./config/gpt2_config.json \
    --model_path \
    --no_cuda \
    --training_steps 3000 \
    --warmup_steps 200 \
    --batch_size 100 \
    --train_data_path ./data/train.txt\
    --train_data_size 20000 \
    --eval_data_path ./data/eval.txt\
    --eval_data_size 600 \
    --no_checkpoint \
    --log_interval 200 \
    --debugging &
