python train.py \
    --model_type gpt2 \
    --config_path ./config/gpt2-config.json \
    --no_cuda \
    --training_steps 3000 \
    --warmup_steps 200 \
    --batch_size 100 \
    --train_data_path train.pkl \
    --eval_data_path eval.pkl \
    --no_checkpoint \
    --log_interval 200 \
    --debugging
